TEAM-DoDream/DoDream_BE

gradle/db.gradle
이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- 8.0.33버전과 Hikari 충돌로 인한 버전 변경
#42
=> Fix(#42): mysql connector 버전을 변경한다.

src/main/java/com/dodream/region/application/RegionService.java, src/main/java/com/dodream/region/presentation/controller/RegionController.java
이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- 중복 파일 삭제과정에서 누락된 import를 추가한다.
#53
=> Fix(#53) ci과정시 생기는 오류를 수정한다

src/main/java/com/dodream/region/presentation/controller/RegionController.java, src/main/java/com/dodream/region/presentation/swagger/RegionSwagger.java
이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- RegionController에 Swagger설정 추가
- @Validated 어노테이션 추가로 오류 해결
#55 
- 후 드디어 지역 끝.. 이제 ncs...
=> Feat(#55): Region 검색 컨트롤러에 Swagger 설명을 추가한다.

src/main/java/com/dodream/member/application/MemberAuthService.java, src/main/java/com/dodream/member/dto/response/MemberLoginResponseDto.java
이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- 닉네임 포함해서 반환하도록 변경
본인이 작업한 내용이 어떤 Issue Number와 관련이 있는지만 작성해주세요
#92
=> Refactor(#92): 로그인시 닉네임 포함해서 반환하도록 변경

src/main/resources/data.sql
=> Fix(#109): data.sql 수정을 통한 데이터 입력 오류를 해결한다

gradle/spring.gradle, src/main/java/com/dodream/member/dto/request/ChangeMemberBirthDateRequestDto.java, src/main/java/com/dodream/member/dto/request/MemberSignUpRequestDto.java, src/main/java/com/dodream/member/presentation/swagger/MemberAuthSwagger.java
- build.gradle에 validation관련 설정 추가
- 회원가입 및 로그인 관련 requestdto의 유효성 검증 어노테이션 수정
#114
=> Refactor(#114) : validation 관련 annotation과 gradle을 수정한다.

src/main/java/com/dodream/recruit/infrastructure/RecruitApiCaller.java, src/main/java/com/dodream/recruit/infrastructure/RecruitFeignClient.java, src/main/java/com/dodream/training/infrastructure/caller/BootCampApiCaller.java, src/main/java/com/dodream/training/infrastructure/caller/DualTrainingApiCaller.java
- 사람인 API 버그 관련으로 마감일 검색기능을 비활성화 처리 했습니다
- API는 원래대로 호출하면 되지만 공고 마감일을 통한 검색이 불가능 합니다.
#123
=> Fix(#123): 사람인 API 버그 개선전까지 마감일 검색 기능을 비활성화 한다.

src/main/java/com/dodream/recruit/dto/response/RecruitResponseListDto.java
- 채용정보 api의 회사정보 누락을 해결한다.
#135
=> Fix(#135): 채용정보 api의 회사명 누락 해결

src/main/java/com/dodream/job/application/JobService.java, src/main/java/com/dodream/job/controller/JobController.java, src/main/java/com/dodream/job/controller/swagger/JobSwagger.java
=> Fix(#138): 직업 list 반환 page로 변경

src/main/java/com/dodream/job/dto/response/JobResponseDto.java
=> Fix(#141): 직업 상세정보 dto에 직업 id 추가"

src/main/java/com/dodream/recruit/dto/response/RecruitResponseListDto.java
=> Fix(#148): 채용정보 api 호출시 locName NPE를 해결한다

src/main/java/com/dodream/recruit/dto/response/RecruitResponseListDto.java, src/main/java/com/dodream/recruit/infrastructure/RecruitApiCaller.java, src/main/java/com/dodream/recruit/infrastructure/RecruitFeignClient.java
- 마감일 관련 검색 기능을 추가했습니다(완벽하진 않지만 마감일 넣고 검색시 오류 발생 x)
- 마감일 역순으로 가장 먼저 마감되는 공고를 기준으로 정렬되어 검색되도록 설정했습니다.
#149
=> Feat(#149): 채용정보 필터를 구체화한다.

src/main/java/com/dodream/todo/application/TodoService.java, src/main/java/com/dodream/todo/dto/response/GetOneTodoGroupResponseDto.java
- 타유저 투두리스트 조회 프로필 사진 추가
- 서브모듈 코드 변경 (이미지 최대 크기지정)
#184
=> Refactor(#184) : 타유저 투두리스트 조회 프로필 사진 추가한다.

src/main/java/com/dodream/recruit/application/RecruitService.java
- 유저가 직업을 담지 않은 경우에 예외처리를 없애고 인기직업으로 검색하도록 합니다.
#215
=> Fix(#215): 유저가 직업담기를 하지않은 경우에 예외처리 수정

.github/ISSUE_TEMPLATE/chore.md, .github/ISSUE_TEMPLATE/cicd.md, .github/ISSUE_TEMPLATE/docs.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/refactor.md
=> Chore(#235) : 이슈 템플릿을 추가한다.

src/main/java/com/dodream/core/infrastructure/log/LoggingAspect.java
- logController - catch문에 throw문을 추가
#247
=> bugfix : logController - catch문에 throw문을 추가한다.

src/main/java/com/dodream/job/domain/TodoCategory.java
- 직업 todo enum 값을 변경한다 (시작하기,도전하기 -> 새싹단계,,,)
#260
=> Refactor(#260) : 직업 todo enum 값을 변경한다

src/main/java/com/dodream/core/config/security/SecurityConfiguration.java, src/main/java/com/dodream/todo/application/TodoCommunityService.java, src/main/java/com/dodream/todo/domain/Todo.java, src/main/java/com/dodream/todo/dto/response/OtherTodoSaveResponseDto.java, src/main/java/com/dodream/todo/dto/response/TodoCommunityResponse.java, src/main/java/com/dodream/todo/dto/response/TodoCommunityResponseDto.java, src/main/java/com/dodream/todo/exception/TodoErrorCode.java, src/main/java/com/dodream/todo/presentation/controller/TodoCommunityController.java, src/main/java/com/dodream/todo/presentation/swagger/TodoCommunitySwagger.java, src/main/java/com/dodream/todo/repository/TodoRepository.java, src/main/java/com/dodream/todo/repository/TodoRepositoryCustom.java, src/main/java/com/dodream/todo/repository/TodoRepositoryImpl.java, src/main/java/com/dodream/todo/util/ConvertLocalDateToString.java
=> Feat(#257): 커뮤니티기능 API 구현

src/main/java/com/dodream/job/repository/JobTodoRepository.java, src/main/java/com/dodream/todo/application/TodoMemberService.java, src/main/java/com/dodream/todo/domain/Todo.java, src/main/java/com/dodream/todo/dto/response/AddTodoResponseDto.java, src/main/java/com/dodream/todo/presentation/controller/TodoMemberController.java, src/main/java/com/dodream/todo/presentation/swagger/TodoMemberSwagger.java
- 직업 개별 투두 하나 추가하기 api 구현
#267
=> Feat(#267) : 직업 개별 투두 하나 추가하기 api 구현

src/main/java/com/dodream/todo/application/TodoService.java, src/main/java/com/dodream/todo/presentation/controller/TodoController.java, src/main/java/com/dodream/todo/repository/TodoGroupRepository.java
=> fix (#275) : 연관된 투두 중복되지 않게 수정
